---
title: Projecto BD
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: cseabra@simplementit.com
description: 'Este é um exemplo de teste com an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: "/tuturial286.github.io"
url: ''
twitter_username: 
github_username: MMiguel1925
sass:
  sass_dir: _sass
markdown: 
